version: 1.0.{build}

branches:
  only:
  - master

clone_folder: c:\dev\wysiwyd

environment:
  ACE_ROOT:          c:/Program Files (x86)/robotology/ace-6.1.1
  GSL_DIR:           c:/Program Files (x86)/robotology/gsl-1.14
  IPOPT_DIR:         c:/Program Files (x86)/robotology/ipopt-3.10.1
  OpenCV_DIR:        c:/Program Files (x86)/robotology/opencv-2.4.9
  Qt5_DIR:           c:/Program Files (x86)/robotology/Qt-5.4.1_v12_x86
  YARP_DIR:          c:/Program Files (x86)/robotology/yarp-2.3.64
  ICUB_DIR:          c:/Program Files (x86)/robotology/icub-1.1.16
  ICUBcontrib_DIR:   c:/iCubContrib
  CMAKE_PREFIX_PATH: c:/iCubContrib

install:
  # to install unzipper do: "cinst 7zip.commandline -x86"
  # the format is: "7z x c:\path-to-archive\archive.zip -oc:\path-where-unzip -y > nul"

  - ps: >-
      $dwntool = New-Object System.Net.WebClient

      $Stoploop = $false

      do {
          try {
            $dwntool.DownloadFile('https://github.com/robotology/yarp/releases/download/v2.3.64/yarp_2.3.64_v12_x86_1.exe','c:\dev\yarp.exe')
            $dwntool.DownloadFile('https://github.com/robotology/icub-main/releases/download/v1.1.16/iCub_1.1.16_v12_x86_2.exe','c:\dev\icub.exe')
            $dwntool.DownloadFile('https://raw.githubusercontent.com/robotology/icub-main/master/conf/iCubHelpers.cmake','c:\dev\iCubHelpers.cmake')
            $Stoploop = $true
          }
          catch {
            Start-Sleep -Seconds 15
          }
      }
      While ($Stoploop -eq $false)

  - cmd: start "" /WAIT "c:\dev\yarp.exe" /S
  - cmd: timeout 10
  - cmd: start "" /WAIT "c:\dev\icub.exe" /S
  - cmd: timeout 10
  - cmd: dir "c:\Program Files (x86)\robotology"

  # temporary fix: apply patch for macro icub_export_library() to install correctly trees of headers
  - ps:  copy-item c:\dev\iCubHelpers.cmake $env:ICUB_DIR\share\iCub\cmake\iCubHelpers.cmake -Force

  - cmd: git clone https://github.com/robotology/icub-contrib-common.git c:\dev\icub-contrib-common
  - cmd: cd c:\dev\icub-contrib-common
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DCMAKE_INSTALL_PREFIX=c:/iCubContrib -G"Visual Studio 12" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

  - cmd: git clone https://github.com/robotology/kinect-wrapper.git c:\dev\kinect-wrapper
  - cmd: cd c:\dev\kinect-wrapper
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 12" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

build:

build_script:
  - cd c:\dev\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 12" ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  - provider: Email
    to:
      - ugo.pattacini@iit.it
      - t.fischer@imperial.ac.uk
      - m.petit@imperial.ac.uk
      - anne.laure.mealier@gmail.com
      - gregoire.pointeau@inserm.fr
      - matej.hoffmann@iit.it
      - clement.moulinfrier@gmail.com
      - dcamilleri1@sheffield.ac.uk
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
