version: 1.0.{build}

branches:
  only:
  - master
  - devel

clone_folder: c:\dev\wysiwyd

environment:
  ACE_ROOT:          c:/Program Files (x86)/robotology/ace-6.3.4_v12_x86
  GSL_DIR:           c:/Program Files (x86)/robotology/gsl-1.14
  IPOPT_DIR:         c:/Program Files (x86)/robotology/ipopt-3.11.7
  OpenCV_DIR:        c:/Program Files (x86)/robotology/opencv-2.4.9
  Qt5_DIR:           c:/Program Files (x86)/robotology/Qt-5.4.1_v12_x86
  YARP_DIR:          c:/Program Files (x86)/robotology/yarp-2.3.65
  ICUB_DIR:          c:/Program Files (x86)/robotology/icub-1.1.17
  ICUBcontrib_DIR:   c:/iCubContrib
  CMAKE_PREFIX_PATH: c:/iCubContrib

install:
  # to install unzipper do: "cinst 7zip.commandline -x86"
  # the format is: "7z x c:\path-to-archive\archive.zip -oc:\path-where-unzip -y > nul"

  - ps: >-
      $dwntool = New-Object System.Net.WebClient

      $Stoploop = $false

      do {
          try {
            $dwntool.DownloadFile('https://github.com/robotology/yarp/releases/download/v2.3.65/yarp_2.3.65_v12_x86_1.exe','c:\dev\yarp.exe')
            $dwntool.DownloadFile('https://github.com/robotology/icub-main/releases/download/v1.1.17/iCub_1.1.17_v12_x86_1.exe','c:\dev\icub.exe')
            $Stoploop = $true
          }
          catch {
            Start-Sleep -Seconds 15
          }
      }
      While ($Stoploop -eq $false)

  - cmd: start "" /WAIT "c:\dev\yarp.exe" /S
  - cmd: timeout 10
  - cmd: start "" /WAIT "c:\dev\icub.exe" /S
  - cmd: timeout 10
  - cmd: dir "c:\Program Files (x86)\robotology"

  - cmd: git clone https://github.com/robotology/icub-contrib-common.git c:\dev\icub-contrib-common
  - cmd: cd c:\dev\icub-contrib-common
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -DCMAKE_INSTALL_PREFIX=c:/iCubContrib -G"Visual Studio 12" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

  - cmd: git clone https://github.com/robotology/kinect-wrapper.git c:\dev\kinect-wrapper
  - cmd: cd c:\dev\kinect-wrapper
  - cmd: md build
  - cmd: cd build
  - cmd: cmake -G"Visual Studio 12" ..
  - cmd: msbuild /m /p:Configuration=Release /p:Platform="Win32" INSTALL.vcxproj

build:

build_script:
  - cd c:\dev\wysiwyd\main
  - md build
  - cd build
  - cmake -G"Visual Studio 12" -DWYSIWYD_BUILD_IOL2OPC=FALSE ..
  - msbuild /m /p:Configuration=Release /p:Platform="Win32" wysiwyd.sln

notifications:
  - provider: Email
    to:
      - wysiwyd-technical@googlegroups.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
